name: Build and deploy Hugo site to GitHub Pages

on:
  push:
    branches: [main]        # or master—use your default branch name

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1.  Fetch your repo with submodules (theme)
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    # 2.  Install Node (for PostCSS) – Hugo needs postcss-cli, autoprefixer, postcss-import
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install PostCSS plugins
      run: |
        npm ci || npm install --save-dev postcss-cli autoprefixer postcss-import

    # 3.  Install Hugo Extended
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.147.6'
        extended: true

    - name: Install Dart Sass
      run: |
        VER=1.89.0
        curl -L \
          https://github.com/sass/dart-sass/releases/download/${VER}/dart-sass-${VER}-linux-x64.tar.gz \
          -o /tmp/dart-sass.tgz

        sudo mkdir -p /usr/local/lib
        sudo tar -xzf /tmp/dart-sass.tgz -C /usr/local/lib     # keeps full tree
        sudo ln -sf /usr/local/lib/dart-sass/sass /usr/local/bin/sass

        sass --embedded --version      # sanity-check


    # 4.  Build the site (outputs to ./public)
    - run: hugo --minify

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
